version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: teste
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  api:
    build: ./backend # Caminho para a pasta do backend
    container_name: api-barbearia
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/teste?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./front/teste # Caminho para a pasta do frontend
    container_name: frontend-barbearia
    ports:
      - "5173:80" # Acess√≠vel em localhost:5173
    depends_on:
      - api